### ISSUE TITLE
Update build system

### ISSUE THREAD

**Issue by maxnus** [BoothGroup/Vayesta#145]
The build system should be brought up to date: we should get rid of `setup.py` and replace `setuptools` with a modern tool (hatchling, poetry, etc)

**Comment by obackhouse** [comment]
The `setup.py` only exists for the compiled bits at this point - if we had no C code I'd just use `pyproject.toml`. I've no experience modernising the compiled bits.

**Comment by maxnus** [comment]
Thanks. I had a look into it and to my surprise, almost no modern build systems support C extension modules, not a good look!
The one exception is poetry, which kind of does (but not stable and documented), but under the hood uses setuptools for this, just that `setup.py` gets renamed to `build.py` - probably not worth the effort at that point.
