### ISSUE TITLE
Translation of fragment not orthogonal to original fragment

### ISSUE THREAD

**Issue by efertitta** [BoothGroup/Vayesta#158]
I encountered the following error during fragmentation when calling for the externally corrected CCSD, with an orbital filter (relevant part of the input below). It seems it's not an issue in Vayesta but a problem caused by asymmetry in the MF (it works fine in Gamma, but fails with larger k-point grid). How can be addressed?

```
[CRITICAL]|      Translation(0.000000,0.000000,0.500000) of fragment Co not orthogonal to original fragment (overlap= 1.0e+00)!
Traceback (most recent call last):
  File "/cluster/projects/nn8040k/SEP-QUEST/BIGMAP/LiCoO2/KPOINTS/Vayesta_GTH_GDF_FCI_ext_method2/version2/LiCoO2_primitive/K_2/cell_111/spin_0/Embedding.py", line 80, in <module>
    with emb.iao_fragmentation() as f:
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/Vayesta/vayesta/core/fragmentation/fragmentation.py", line 74, in __exit__
    fragments_sym = self.emb.create_transsym_fragments(translation, fragments=self.fragments)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/Vayesta/vayesta/core/qemb/qemb.py", line 1045, in create_transsym_fragments
    return self.create_symmetric_fragments(symmetry, fragments=fragments, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/Vayesta/vayesta/core/qemb/qemb.py", line 928, in create_symmetric_fragments
    raise RuntimeError("Overlapping fragment spaces (overlap= %.1e)" % fragovlp)
RuntimeError: Overlapping fragment spaces (overlap= 1.0e+00)

```

INPUT

```
emb = vayesta.ewf.EWF(mf, solver='CCSD', bath_options=dict(bathtype='mp2', threshold=eta))
fci_frags = []
with emb.iao_fragmentation() as f:
    fci_frags.append(f.add_atomic_fragment('Co', orbital_filter=['3d'], solver="FCI", bath_options=dict(bathtype="dmet"), store_wf_type="CCSDTQ", auxiliary=True))
    ccsd_frags = f.add_all_atomic_fragments(solver="CCSD", bath_options=dict(bathtype="mp2", threshold=eta))
for cc_frag in ccsd_frags:
    cc_frag.add_external_corrections(fci_frags, correction_type="external", projectors=2, low_level_coul=False)
emb.kernel()
```

**Comment by ghb24** [comment]
Can you provide the pyscf input to create the mf object?

**Comment by efertitta** [comment]
import sys, os
from functools import reduce
import numpy as np
import pyscf
from pyscf import gto as gto_mol
from pyscf.pbc import gto, scf, df, dft
from pyscf import ao2mo, lo
from pyscf.tools import fcidump, molden
import iao_utils.poscar2pyscf as pospy
from pyscf import scf as mol_scf
from pyscf import cc, mp, ci, mcscf
import pyscf.pbc.tools as pbctools

import vayesta
import vayesta.ewf
from vayesta.mpi import mpi
from scipy.linalg import block_diag

here = os.path.dirname(__file__)

geom_file=os.path.join(here,'LiCoO2_primitive.vasp')
basiset = 'gth-dzvp-molopt-sr'
pseudo = 'gth-hf-rev'
basis_ri = 'def2-qzvpp-ri'

scaling = [1., 1., 1.]
ncells = int(scaling[0]*scaling[1]*scaling[2])
spincell = 0*ncells

cell = gto.Cell()
cell.a, cell.atom = pospy.read_poscar(geom_file, scaling = scaling)

cell.spin = spincell
cell.unit = 'A'
cell.verbose = 4
cell.basis= basiset
cell.pseudo=pseudo
cell.ke_cutoff = 200.0
cell.precision = 1.e-8
cell.build()

kpts = cell.make_kpts([2]*3)

print('Running HF')
mf = scf.KRHF(cell, kpts)
mf.with_df = df.GDF(cell, kpts)
mf.with_df.auxbasis = basis_ri
mf.level_shift = 0.05
mf.max_cycle = 700
mf.chkfile = os.path.join(here,'hf.chk')
mf.kernel()

with open(os.path.join(here,'energies.txt'), 'a') as f:
        f.write('%6s %16.8f\n' % ('HF', mf.e_tot))

etas = [1.e-3, 1.e-4, 1.e-5, 1.e-6, 1.e-7, 1.e-8, 1.e-9, 1.e-10]
for eta in etas:
  emb = vayesta.ewf.EWF(mf, solver='CCSD', bath_options=dict(bathtype='mp2', threshold=eta), solver_options=dict(diis_space=12, level_shift=0.05, diis_start_cycle = 2))

  # Externally corrected with only Co
  fci_frags = []
  with emb.iao_fragmentation() as f:
      fci_frags.append(f.add_atomic_fragment('Co', solver="FCI", bath_options=dict(bathtype="dmet"), store_wf_type="CCSDTQ", auxiliary=True))
      ccsd_frags = f.add_all_atomic_fragments(solver="CCSD", bath_options=dict(bathtype="mp2", threshold=eta))

  for cc_frag in ccsd_frags:
      cc_frag.add_external_corrections(fci_frags, correction_type="external", projectors=2, low_level_coul=False)

  emb.kernel()
  e_wf = emb.get_wf_energy()
  e_dm_incluster_cumulant = emb.get_dm_energy()

  eta_string = '%.2e'%eta
  if mpi.is_master:
    with open(os.path.join(here,'energies.txt'), 'a') as f:
      f.write('%6s %16.8f %16.8f\n' % (
               eta_string , e_wf, e_dm_incluster_cumulant))

**Comment by efertitta** [comment]
LiCoO2_primitive.vasp file

```
Li Co O2
1.0
   1.4056284884  0.8115399862   4.6364854775
  -1.4056284884  0.8115399862   4.6364854775
  -0.0000000000 -1.6230799723   4.6364854775
Li Co O
1 1 2
direct
0.0000000000    0.0000000000    0.0000000000
0.5000000000    0.5000000000    -0.5000000000
0.2400068000    0.2400068000    0.2400068000
0.7599932000    -0.2400068000   -0.2400068000
```

**Comment by efertitta** [comment]
hi @ghb24, of course, this is the mf part
```
import os
import numpy as np
import pyscf
from pyscf.pbc import gto, scf, df

here = os.path.dirname(__file__)

cell = gto.Cell()

cell.a = np.array([[ 1.40562849,  0.81153999,  4.63648548],[-1.40562849,  0.81153999,  4.63648548],[ 0.,         -1.62307997,  4.63648548]])
cell.atom = [['Li', [0.0, 0.0, 0.0]], ['Co', [0.0, 1.62307997235, 2.31824273875]], ['O', [-6.492169233150939e-19, 2.400065585912509e-11, 3.338364128103741]], ['O', [1.4056284884, 0.8115399861759994, 1.2981213493962593]]]

cell.spin = 0
cell.unit = 'A'
cell.verbose = 4
cell.basis= 'gth-dzvp-molopt-sr'
cell.pseudo='gth-hf-rev'
cell.ke_cutoff = 200.0
cell.precision = 1.e-8
cell.build()

kpts = cell.make_kpts([2]*3)

print('Running HF')
mf = scf.KRHF(cell, kpts)
mf.with_df = df.GDF(cell, kpts)
mf.with_df.auxbasis = 'def2-qzvpp-ri'
mf.level_shift = 0.05
mf.max_cycle = 700
mf.chkfile = os.path.join(here,'hf.chk')
mf.kernel()
```

**Comment by efertitta** [comment]
Here is how I am attempting the Externally correction with FCI run on Cobalt only
```
emb = vayesta.ewf.EWF(mf, solver='CCSD', bath_options=dict(bathtype='mp2', threshold=1.e-3), solver_options=dict(diis_space=12, level_shift=0.05, diis_start_cycle = 2))

fci_frags = []
with emb.iao_fragmentation() as f:
    fci_frags.append(f.add_atomic_fragment('Co', solver="FCI", bath_options=dict(bathtype="dmet"), store_wf_type="CCSDTQ", auxiliary=True))
    ccsd_frags = f.add_all_atomic_fragments(solver="CCSD", bath_options=dict(bathtype="mp2", threshold=eta))

for cc_frag in ccsd_frags:
     cc_frag.add_external_corrections(fci_frags, correction_type="external", projectors=1)

emb.kernel()
```

**Comment by ghb24** [comment]
@abhishekkhedkar09 : Could you test this? I think it should be as simple as adding
```
cell.space_group_symmetry = True
cell.symmorphic = True
```
before the cell.build()
and
`kpts = cell.make_kpts([2, 2, 2], space_group_symmetry=True, time_reversal_symmetry=True, symmorphic=True)
` to the kpnt builder, to enforce time-reversal symmetry...?

**Comment by efertitta** [comment]
I tried your suggestions but did not help, unfortunately
What I was trying to do was to have FCI solved only on 3d of Co and use this to correct the CCSD part as such:

```
emb = vayesta.ewf.EWF(mf, solver='CCSD', bath_options=dict(bathtype='mp2', threshold=1.e-3))
fci_frags = []
with emb.iao_fragmentation() as f:
    fci_frags.append(f.add_atomic_fragment('Co', orbital_filter=['3d'], solver="FCI", bath_options=dict(bathtype="dmet"), store_wf_type="CCSDTQ", auxiliary=True))
    ccsd_frags = f.add_all_atomic_fragments(solver="CCSD", bath_options=dict(bathtype="mp2", threshold=eta))
for cc_frag in ccsd_frags:
     cc_frag.add_external_corrections(fci_frags, correction_type="external", projectors=1)
emb.kernel()
```
This does not work, however I noticed that if you call for `f.add_all_atomic_fragments` the fragmentation proceeds smoothly (but the FCI crashes because the full DMET space for Co is too large)
So I tried to use the following workaround based on the same syntax in `f.add_all_atomic_fragments` and this actually works without any problem

```
emb = vayesta.ewf.EWF(mf, solver='CCSD', bath_options=dict(bathtype='mp2', threshold=1.e-3))
fci_frags = []
with emb.iao_fragmentation() as f:
      for atom in range(emb.kcell.natm):
          if atom == 1: #Co-index is 1
             fci_frags.append(f.add_atomic_fragment(atom, orbital_filter=['3d'], solver="FCI", bath_options=dict(bathtype="dmet"), store_wf_type="CCSDTQ", auxiliary=True))
      ccsd_frags = f.add_all_atomic_fragments(solver="CCSD", bath_options=dict(bathtype="mp2", threshold=eta))
for cc_frag in ccsd_frags:
     cc_frag.add_external_corrections(fci_frags, correction_type="external", projectors=1)
emb.kernel()

```
Why does this work? Am I now adding the Co fragments in every cell and symmetrizing afterwards???

**Comment by abhishekkhedkar09** [comment]
@efertitta I will test the above two as well and get back to you. Could you please provide the  error you get in the first one above? If passed a string to `add_atomic_fragment('Co' ...` it is converted into a list in Vayesta so it should work...

**Comment by efertitta** [comment]
@abhishekkhedkar09 I get the following error when using the first syntax above
```
[CRITICAL]|      Translation(0.000000,0.000000,0.500000) of fragment Co not orthogonal to original fragment (overlap= 1.0e+00)!
Traceback (most recent call last):
  File "/cluster/projects/nn8040k/SEP-QUEST/BIGMAP/LiCoO2/KPOINTS/Vayesta_GTH_GDF_FCI_ext_method2/version2/LiCoO2_primitive/K_2/cell_111/spin_0/Embedding.py", line 80, in <module>
    with emb.iao_fragmentation() as f:
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/Vayesta/vayesta/core/fragmentation/fragmentation.py", line 74, in __exit__
    fragments_sym = self.emb.create_transsym_fragments(translation, fragments=self.fragments)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/Vayesta/vayesta/core/qemb/qemb.py", line 1045, in create_transsym_fragments
    return self.create_symmetric_fragments(symmetry, fragments=fragments, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/edoardof/.local/lib/python3.11/site-packages/Vayesta/vayesta/core/qemb/qemb.py", line 928, in create_symmetric_fragments
    raise RuntimeError("Overlapping fragment spaces (overlap= %.1e)" % fragovlp)
RuntimeError: Overlapping fragment spaces (overlap= 1.0e+00)
```

**Comment by abhishekkhedkar09** [comment]
@efertitta 
Turns out specifying atomic fragments by string method like this: "Co" selects all (in this case, 8) instances of "Co" atoms into a single fragment. We will have this behaviour fixed soon, but in the meantime specifying add_atomic_fragment([1] ... ) should fix the problem...

**Comment by abhishekkhedkar09** [comment]
I have marked this issue with `enhancement` feature request so that we'd circle back to this.
