### ISSUE TITLE
Errors in examples due to compatability with pyscf 2.3.0/2.4.0

### ISSUE THREAD

**Issue by efertitta** [BoothGroup/Vayesta#159]
Problem 1
In pyscf 2.3.0 calling GDF as:
```
mf = scf.KRHF(cell, kpt).density_fit()
```
does not give the same results as 
```
mf = scf.KRHF(cell, kpt)
mf.with_df = df-df.GDF(cell, kpt)
```
The second approach is reliable (See https://github.com/pyscf/pyscf/issues/1975)
The issue was solved in 2.4.0 but beware that most of Vayesta examples use the first notation

Problem 2
Example 61 will not work with pyscf 2.4.0 but it will 2.3.0
The error occurs in `fold_scf(mf)` if `lda_as_hf.__dict__.update(lda.__dict__)` is called as in the example. As a (rather ugly) workaround I tried to specify the entries of the dictionary manually (mo_occ, mo_coeff, mo_energy etc) and that worked...

**Comment by basilib** [comment]
Could you please provide an example script. I can't reproduce these issues. Example ewf/molecules/61-lda.py works with the latest pyscf.
