### ISSUE TITLE
Issues with built in solvers with no virtual orbitals

### ISSUE THREAD

**Issue by Connorpl** [BoothGroup/Vayesta#181]
```
import numpy as np
import pyscf
import pyscf.gto
import pyscf.scf
import pyscf.fci
import pyscf.pbc

import vayesta
import vayesta.ewf
from vayesta.misc.molecules import ring
from vayesta.core.types.wf.t_to_c import t1_uhf, t2_uhf
from vayesta.solver.ccsd import UCCSD
from vayesta.solver.cisd import UCISD


import sys, os
from os import environ
from itertools import product as prod




from pyscf.pbc.gto import Cell
from pyscf.pbc import scf as pbcscf
from vayesta.misc import solids
from vayesta.misc.gto_helper import get_atom_shells

from pyscf.pbc import cc as cup_clus
from pyscf import scf
from pyscf.lib import chkfile

# User defined FCI solver - takes pyscf mf as input and returns RDMs
# The mf argment contains the hamiltonain in the orthonormal cluster basis
# Pyscf or other solvers may be used to solve the cluster problem and may return RDMs, CISD amplitudes or CCSD amplitudes



do_ccsd = 0#bool(int(sys.argv[5]))


from datetime import datetime

now = datetime.now() # current date and time

#4.1705
# for atomic_dis in [4.1705]:#np.arange(float(sys.argv[2]),float(sys.argv[3]),float(sys.argv[4])):
#     kmesh  = [1,1,1]
#     for magnetism in magnetics:

atomic_dis = 4.1705
magnetism = "AFM1_HS"
# magnetism = "AFM2"
basis, pseudo = "gth-dzvp-molopt-sr", "gth-pade"
kmesh = [1,1,1]

kmeshstr = "".join(map(str, kmesh))



unitcell = "primitive-af1" if "AFM1" in magnetism else "primitive-af2"

cell = Cell()
cell.a, cell.atom = solids.rocksalt(
    atoms=["Ni", "O"], a=atomic_dis, unitcell=unitcell
)  # Oxide
cell.basis = basis
cell.pseudo = pseudo
cell.output = f"{kmeshstr}_"+now.strftime("%d")+"_"+now.strftime("%m")+"_"+now.strftime("%Y")+"_"+now.strftime("%H")+"_"+now.strftime("%M")+"_"+now.strftime("%S")+"_pyscf.txt"
cell.verbose = 5
cell.spin = 4 * np.product(kmesh) if "HS" in magnetism else 0  # Oxide
cell.exp_to_discard = 0.1

cell.build()
kpts = cell.make_kpts(kmesh, time_reversal_symmetry=False)

local_spin = None
fm_to_afm = False

mf = pbcscf.KUHF(cell, kpts)
mf = mf.density_fit()

df = mf.with_df
dm = mf.get_init_guess()


mf.kernel(dm0=dm)
mf.max_cycle = 250
if not mf.converged:
    dm0 = mf.make_rdm1()
    mf = mf.newton()
    mf.kernel(dm0)

assert mf.converged


mf.analyze()
print("Hartree-Fock energy          : %s"%mf.e_tot)




# CCSD
if do_ccsd:
    mf2 = scf.addons.remove_linear_dep_(mf).run()
    cc = cup_clus.KUCCSD(mf2)
    cc.kernel()



# Vayesta options
use_sym = False
nfrag = 1 
bath_type = "dmet"
bath_opts = dict(bathtype=bath_type)   


# bnoeta = 1e-2
# bath_opts=dict(bathtype="mp2", threshold=bnoeta) 

ncells = np.product(kmesh)
emb = vayesta.ewf.EWF(mf, solver="FCI",  energy_functional='wf', bath_options=bath_opts)
# Set up fragments
with emb.iao_fragmentation() as f:
    f.add_atomic_fragment([0], orbital_filter=["Ni 3dxz","Ni 3dxy","Ni 3dyz"])
    f.add_atomic_fragment([0], orbital_filter=["Ni 3s","Ni 3p"])
    f.add_atomic_fragment([0], orbital_filter=["Ni 3dx2-y2","Ni 3dz\^2","Ni 4s","Ni 4p"])

    f.add_atomic_fragment([1], orbital_filter=["O 2s","O 2p", "O 3s"])

    f.add_atomic_fragment([2], orbital_filter=["Ni 3s","Ni 3p"])
    f.add_atomic_fragment([2], orbital_filter=["Ni 3dxz","Ni 3dxy","Ni 3dyz"])
    f.add_atomic_fragment([2], orbital_filter=["Ni 3dx2-y2","Ni 3dz\^2","Ni 4s","Ni 4p"])

    f.add_atomic_fragment([3], orbital_filter=["O 2s","O 2p", "O 3s"])

emb.kernel()
```

**In the above code I have run into a series of issues which seem to be caused by the small cluster sizes creating clusters with unequal numbers of orbitals on each spin or no orbitals on one of the spins.** 

e.g.

Making bath and clusters for Fragment 0: Ni
          |  -------------------------------------------
          |      Making DMET Bath
          |      ----------------
          |          Making alpha-DMET bath
          |          DMET bath:  n(Bath)=    0  n(occ-Env)=   23  n(vir-Env)=   52
          |          Entanglement entropy: total= 7.874e-15  bath= 0.000e+00 (0.00 %)
          |          Making beta-DMET bath
          |          DMET bath:  n(Bath)=    2  n(occ-Env)=   19  n(vir-Env)=   54
          |          Mean-field entangled orbitals:
          |                Bath  Occupation  Entanglement  Character
          |                ----  ----------  ------------  ------------------------------------------------------
          |             1   Yes         0.5             1  Ni 3dxy (103%), Ni 4dxy (0%), O 3dxy (0%), O 3dxy (0%)
          |             2   Yes         0.5             1  Ni 3dyz (103%), Ni 4dyz (0%), O 3dyz (0%), O 3dyz (0%)
          |          Entanglement entropy: total= 5.000e-01  bath= 5.000e-01 (100.00 %)
          |          Alpha-cluster orbitals:  n(occ)=   3  n(vir)=   0
          |           Beta-cluster orbitals:  n(occ)=   3  n(vir)=   2
          |      Orbitals for Fragment 0: Ni
          |      ---------------------------
          |                   Active                   Frozen                   Total
          |                   ----------------------   ----------------------   ------------
          |        Occupied       3,     3 (  12.5%)      23,    19 (  87.5%)      26,    22
          |        Virtual        0,     2 (   1.9%)      52,    54 (  98.1%)      52,    56
          |        Total          3,     5 (   5.1%)      75,    73 (  94.9%)      78,    78

 initially this causes an error:

File "/Documents/Quantum_cluster/FCI_error_script.py", line 435, in <module>
  File "/.local/lib/python3.11/site-packages/vayesta/ewf/ewf.py", line 168, in kernel
    x.kernel()
  File "/.local/lib/python3.11/site-packages/vayesta/ewf/fragment.py", line 261, in kernel
    pwf = wf.as_cisd()
          ^^^^^^^^^^^^
  File "/.local/lib/python3.11/site-packages/vayesta/core/types/wf/fci.py", line 563, in as_cisd
    self.check_norb()
    ^^^^^^^^^^^^^^^
AttributeError: 'UFCI_WaveFunction_w_dummy' object has no attribute 'check_norb'

**which can be fixed by removing the call to the check_norb attribute which is not defined. 
This just reveals another error:**

Traceback (most recent call last):
  File "/.local/lib/python3.10/site-packages/vayesta/ewf/ewf.py", line 168, in kernel
    x.kernel()
  File "/.local/lib/python3.10/site-packages/vayesta/ewf/fragment.py", line 261, in kernel
    pwf = wf.as_cisd()
  File "/.local/lib/python3.10/site-packages/vayesta/core/types/wf/fci.py", line 587, in as_cisd
    c1 = (vsl(c1a, [va]), vsl(c1b, [vb]))
  File "/.local/lib/python3.10/site-packages/vayesta/core/types/wf/fci.py", line 575, in vsl
    return a.transpose()[np.ix_(*sl[::-1])].transpose()
IndexError: arrays used as indices must be of integer (or boolean) type
srun: error: erc-hpc-comp058: task 0: Exited with exit code 1

**(line numbers may be slightly off due to local changes) this appears to be trying to remove the padded virtual orbitals but fails when the array va is empty. I tried to fix this with the following code in core/types/wf/fci.py in the UFCI_WaveFunction_w_dummy attribute as_cisd:**

if va.size == 0 and vb.size!=0:
    c1 = (np.array([[]]), vsl(c1b, [vb]))
    c2 = (np.array([[[[]]]]), np.array([[[[]]]]), vsl(c2bb, [vb, vb]))
elif vb.size==0 and va.size!=0:
    c1 = (vsl(c1a, [va]),np.array([[]]))
    c2 = (vsl(c2aa, [va, va]),np.array([[[[]]]]), np.array([[[[]]]]))
elif va.size==0 and vb.size==0:
    c1 = (np.array([[]]),np.array([[]]))
    c2 = (np.array([[[[]]]]),np.array([[[[]]]]), np.array([[[[]]]]))
else:
    c1 = (vsl(c1a, [va]), vsl(c1b, [vb]))
    c2 = (vsl(c2aa, [va, va]), vsl(c2ab, [va, vb]), vsl(c2bb, [vb, vb]))

**which then leads to a new problem:**

Traceback (most recent call last):
  File "/Quantum_cluster/callback_NiO.py", line 431, in <module>
    emb_fci.kernel()
  File "/.local/lib/python3.10/site-packages/vayesta/ewf/ewf.py", line 168, in kernel
    x.kernel()
  File "/.local/lib/python3.10/site-packages/vayesta/ewf/fragment.py", line 274, in kernel
    pwf = pwf.project(proj, inplace=False)
  File "/.local/lib/python3.10/site-packages/vayesta/core/types/wf/cisd.py", line 117, in project
    wf.c1 = project_uc1(wf.c1, projector)
  File "/.local/lib/python3.10/site-packages/vayesta/core/types/wf/project.py", line 28, in project_uc1
    return (project_c1(c1[0], p[0]), project_c1(c1[1], p[1]))
  File "/.local/lib/python3.10/site-packages/vayesta/core/types/wf/project.py", line 12, in project_c1
    return np.dot(p, c1)
ValueError: shapes (3,3) and (1,0) not aligned: 3 (dim 1) != 1 (dim 0)

**this could probably be handled on a case by case basis as well but I am wondering if there is a better solution to this issue than individually handling this in every place it causes a problem. I also tried a CCSD solver instead of an FCI solver and a different error "numpy.linalg.LinAlgError: Singular matrix" is caused.**

**Comment by basilib** [comment]
I have attempted to resolve these issues in #184. 
Let me know if there are still issues which persist.
