### ISSUE TITLE
installing via yml file

### ISSUE THREAD

**Issue by hh2110** [BoothGroup/Vayesta#29]
Hi, I'm trying to install vayesta into an existing conda environment - when I try to do this by inserting `- git+https://github.com/BoothGroup/Vayesta.git@master#egg=Vayesta` into the pip section of my yml file, some files are not downloaded such as the files in `vayesta/solver/eb_fci/*py` and the tests directory. However, if I follow the instructions given in your readme.md, then the `eb_fci` folder is downloaded correctly.

**Comment by maxnus** [comment]
Thanks for reporting this, we are having a look now.

**Comment by maxnus** [comment]
This was closed automatically by merging #30.
@hh210 let us know if this fixes the conda installation for you at all or not

**Comment by hh2110** [comment]
Thanks, it is working as expected now
