### ISSUE TITLE
Example 24 tailoring crashes

### ISSUE THREAD

**Issue by ghb24** [BoothGroup/Vayesta#68]
I don't know whether this is an arm64 issue, but the example ewf/molecules/24-tailor-with-fragments.py is now crashing as it stops converging the CCSD successfully, and eventually hits a numpy.linalg.LinAlgError: Singular matrix in the DIIS - I don't think it was doing this previously. Can other people see this behaviour?
[observed on both master and v1.0.2a branches]

**Comment by basilib** [comment]
This also occurs on an Intel Xeon cpu with openblas.
